{{- if .Values.providerYoutubejs.pdb.enabled }}
{{- $component := "provider-youtubejs" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ypd.componentName" (list . $component) }}
  labels:
    {{- include "ypd.labels" (list . $component) | nindent 4 }}
spec:
  minAvailable: {{ .Values.providerYoutubejs.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "ypd.selectorLabels" (list . $component) | nindent 6 }}
{{- end }}
