{{- $component := "frontend" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ypd.componentName" (list . $component) }}
  labels:
    {{- include "ypd.labels" (list . $component) | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ypd.selectorLabels" (list . $component) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config/frontend.configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "ypd.labels" (list . $component) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ypd.serviceAccountName" (list . "frontend") }}
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: {{ .Values.frontend.terminationGracePeriodSeconds }}
      securityContext:
        {{- include "ypd.podSecurityContext" (list . 1001) | nindent 8 }}
      containers:
        - name: frontend
          image: {{ include "ypd.image" (list . .Values.images.frontend) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
          envFrom:
            - configMapRef:
                name: {{ include "ypd.componentName" (list . "frontend") }}
          env:
            - name: TMPDIR
              value: /tmp
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            {{- include "ypd.containerSecurityContext" (list . .Values.frontend.readOnlyRootFilesystem) | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
